### PR TITLE
change imports to absolute import

### LINKED ISSUE #8: Absolute import refactoring
Refactor imports in all files to use absolute importing

### PR DESCRIPTION
**Pull request by VaradK62442**
note that to now run tests, the following steps need to be followed:
1. clone the project
2. inside the project directory, run `python3 -m build`
3. next, run `pip install dist/*.tar.gz`
4. then in any file you can use `import algmatch` or `from algmatch.studentProjectAllocation import StudentProjectAllocation`, etc.

### CODE REVIEW

**Comment by VaradK62442** [comment]
^ not just to run tests, to use the package generally

**Review by BenOnTheBoard — APPROVED** [review]
This is fine
Could you take a look at my verification branch and let me know if this will fix the problem I was having in smVerifyCorrectness.py? It uses os.path currently.

**Comment by VaradK62442** [comment]
yes, from what i can tell this absolute importing should fix that. you shouldnt need to do anything with os.

**Comment by VaradK62442** [comment]
good to merge in? then can merge from main into your branch too

**Comment by BenOnTheBoard** [comment]
Sorted, I'll delete the branch and then update my testing code when I work on it tomorrow.

**Pull request merged**
